name: MDB AI Prompted Text
description: MindsDB Single-prompted Text Operator Action
author: Sadra Yahyapour

branding:
  icon: check
  color: blue

runs:
  using: docker
  image: Dockerfile

inputs:
  github_token:
    description: The GitHub auth token
    default: ${{ github.token }}
    required: true

  repository:
    description: The repository name in the form of "<owner>/<repo>"
    default: ${{ github.repository }}
    required: true

  issue_number:
    description: The id of the issue
    required: true

  mdb_token:
    description: MindsDB (mdb.ai) api token
    required: true

outputs:
  answer:
    description: The answer returned from mdb.ai
