on:
  issues:
    types: [opened]

jobs:
  Test:
    runs-on: ubuntu-latest
    name: Testing the action
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run action
        uses: ./
        id: ai
        with:
          issue_number: ${{ github.event.issue.number }}
          mdb_token: ${{ secrets.MDB_TOKEN }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.ai.outputs.answer }}
