on:
  issues:
    types: [opened]

jobs:
  Test:
    runs-on: ubuntu-latest
    name: Testing the action
    steps:

      - name: Create processing comment
        uses: peter-evans/create-or-update-comment@v4
        id: comment
        with:
          issue-number: ${{ github.event.issue.number }}
          body: Processing..

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run action
        uses: ./
        id: ai
        with:
          issue_number: ${{ github.event.issue.number }}
          mdb_token: ${{ secrets.MDB_TOKEN }}

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.comment.outputs.comment-id }}
          body: ${{ steps.ai.outputs.answer }}
          reactions: rocket
          edit-mode: replace
